# Generated by Django 4.1.3 on 2022-11-06 06:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("tags", models.ManyToManyField(to="gyvuneliai.tag")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.DeleteModel(
            name="Blog_post",
        ),
    ]
