# Generated by Django 4.1.3 on 2022-11-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0003_animal_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="tags",
        ),
        migrations.AddField(
            model_name="animal",
            name="tags",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="gyvuneliai.tag",
            ),
        ),
    ]
