# Generated by Django 4.1.3 on 2022-11-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0004_remove_animal_tags_animal_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="tags",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="gyvuneliai.tag",
            ),
        ),
    ]
