# Generated by Django 4.1.3 on 2022-11-13 05:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0005_alter_animal_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="age",
            field=models.IntegerField(
                blank=True,
                help_text="Įrašyk gyvūnėlio amžių",
                max_length=2,
                null=True,
                verbose_name="Amžius",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="breed",
            field=models.CharField(
                blank=True,
                help_text="Įrašyk gyvūnėlio veislę",
                max_length=200,
                null=True,
                verbose_name="Veislė",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="weight",
            field=models.IntegerField(
                blank=True,
                help_text="Įrašyk gyvūnėlio svorį",
                max_length=3,
                null=True,
                verbose_name="Svoris",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Jeigu neuždėsi varnelės - įrašas nebus aktyvus, nebus matomas puslapyje",
                verbose_name="Ar įrašas aktyvus? Taip/Ne",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Parašyk trumpą aprašymą apie gyvūnėlį",
                null=True,
                verbose_name="Apie gyvunėlį(temperamentas)",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Išrink ir įkelk gražiausią mažuliuko nuotrauką",
                upload_to="photo/%Y/%m%d",
                verbose_name="Nuotrauka",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tags",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="gyvuneliai.tag",
                verbose_name="Šuo/Katė",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="title",
            field=models.CharField(
                help_text="Įrašyk gyvūnėlio vardą", max_length=50, verbose_name="Vardas"
            ),
        ),
    ]
