# Generated by Django 4.1.3 on 2022-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0006_animal_age_animal_breed_animal_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[("Br", "Berniukas"), ("Mr", "Mergaite")],
                default="Br",
                max_length=10,
                verbose_name="Lytis",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.IntegerField(
                blank=True,
                help_text="Įrašyk gyvūnėlio amžių",
                null=True,
                verbose_name="Amžius",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.IntegerField(
                blank=True,
                help_text="Įrašyk gyvūnėlio svorį",
                null=True,
                verbose_name="Svoris",
            ),
        ),
    ]
