# Generated by Django 4.1.3 on 2022-11-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0007_animal_sex_alter_animal_age_alter_animal_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[("Patelė", "Patelė"), ("Patinas", "Patinas")],
                default="Patinas",
                max_length=10,
                verbose_name="Lytis",
            ),
        ),
    ]
