# Generated by Django 4.1.3 on 2022-11-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0009_animal_good_with_cats_animal_good_with_dogs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="adoption_donation",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Adoption mokestis"
            ),
        ),
    ]
