# Generated by Django 4.1.3 on 2022-11-13 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0010_animal_adoption_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="story",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Parašyk trumpą istoriją/aprašymą apie gyvūnėlį",
                null=True,
                verbose_name="Istorija",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Parašyk trumpą aprašymą apie gyvūnėlį",
                max_length=255,
                null=True,
                verbose_name="Apie gyvunėlį(temperamentas)",
            ),
        ),
    ]
