# Generated by Django 4.1.3 on 2022-11-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0011_animal_story_alter_animal_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="adoption_donation",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Adoption mokestis(eur)"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Parašyk trumpą aprašymą apie gyvūnėlį",
                max_length=255,
                null=True,
                verbose_name="Apibūdink gyvūnėlio temperamentą",
            ),
        ),
    ]
