# Generated by Django 4.1.3 on 2022-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyvuneliai", "0012_alter_animal_adoption_donation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Jeigu neuždėsi varnelės - įrašas nebus matomas puslapyje",
                verbose_name="Ar įrašas aktyvus? Taip/Ne",
            ),
        ),
    ]
